version: 2

project_name: clickhouse-bulk

release:
  github:
    owner: nikepan
    name: clickhouse-bulk

builds:
  - binary: clickhouse-bulk
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - 386
    env:
      - CGO_ENABLED=0
    main: ./
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - config.sample.json
      - README.md
      - LICENSE

dockers:
  - image_templates:
      - "nikepan/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "nikepan/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    extra_files:
      - config.sample.json
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "nikepan/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "nikepan/{{ .ProjectName }}:{{ .Version }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    extra_files:
      - config.sample.json
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "nikepan/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "nikepan/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "nikepan/{{ .ProjectName }}:{{ .Tag }}-arm64"

  - name_template: "nikepan/{{ .ProjectName }}:latest"
    image_templates:
      - "nikepan/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "nikepan/{{ .ProjectName }}:{{ .Version }}-arm64"
